### ISSUE TITLE
[CI] Error: Missing binding[...]/node_modules/node-sass/vendor/linux-x64-48/binding.node  Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x

### ISSUE THREAD

**Issue by hectorj** [wizaplace/starterkit#300]
```

[wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ] Running shell script

+ make npm-install lint-css assets

npm install --no-save

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):

npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none was installed.

npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none was installed.

gulp lint-css

/var/lib/jenkins/workspace/wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ/node_modules/node-sass/lib/binding.js:15

      throw new Error(errors.missingBinary());

      ^



Error: Missing binding /var/lib/jenkins/workspace/wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ/node_modules/node-sass/vendor/linux-x64-48/binding.node

Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x



Found bindings for the following environments:

  - Linux 64-bit with Node.js 7.x



This usually happens because your environment has changed since running `npm install`.

Run `npm rebuild node-sass --force` to build the binding for your current environment.

    at module.exports (/var/lib/jenkins/workspace/wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ/node_modules/node-sass/lib/binding.js:15:13)

    at Object.<anonymous> (/var/lib/jenkins/workspace/wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ/node_modules/node-sass/lib/index.js:14:35)

    at Module._compile (module.js:577:32)

    at Object.Module._extensions..js (module.js:586:10)

    at Module.load (module.js:494:32)

    at tryModuleLoad (module.js:453:12)

    at Function.Module._load (module.js:445:3)

    at Module.require (module.js:504:17)

    at require (internal/module.js:20:19)

    at Object.<anonymous> (/var/lib/jenkins/workspace/wizaplace_starterkit_master-FTPLF4OCXYDHEN6W32UDLBF5WAHGB6LZX54C37CJAK6OUHVKIBRQ/node_modules/gulp-sass/index.js:187:21)

Makefile:38: recipe for target 'lint-css' failed

make: *** [lint-css] Error 1

script returned exit code 2
```

**Comment by hectorj** [comment]
corrigé par un wipe du cache NPM et des dossiers node_modules sur Jenkins
